Repository PlaceOS/driver, pull requests merged in 2021-04, with the labels that each got.

#60 fix(mock_driver): reorder requires
  shard.yml
  src/placeos-driver/driver-specs/mock_driver.cr
Labels: priority: critical, type: bug

#62 fix(protocol/management): reentrant debug lock
  shard.yml
  src/placeos-driver/protocol/management.cr
Labels: type: bug

#64 feat(interface): add electrical relay interface
  src/placeos-driver/interface/electrical_relay.cr
Labels: focus: backend, type: enhancement
