Repository PlaceOS/driver, pull requests merged in 2021-05, with the labels that each got.

#68 fix(interface/electrical_relay): add missing type to #pulse
  shard.yml
  src/placeos-driver/interface/electrical_relay.cr
Labels: type: bug

#65 feat: add json schema to driver metadata
  spec/settings_spec.cr
  spec/test_build.cr
  src/placeos-driver.cr
  src/placeos-driver/driver_model.cr
  src/placeos-driver/settings.cr
  src/placeos-driver/settings/introspect.cr
  src/placeos-driver/transport/ssh.cr
Labels: focus: backend, focus: documentation, type: enhancement

#70 feat(metadata): use json schema for function arguments
  .github/workflows/ci.yml
  shard.yml
  spec/driver_proxy_spec.cr
  spec/driver_spec.cr
  spec/drivers_proxy_spec.cr
  spec/scheduler_spec.cr
  spec/settings_spec.cr
  src/placeos-driver.cr
  src/placeos-driver/driver_model.cr
  src/placeos-driver/proxy/driver.cr
  src/placeos-driver/proxy/scheduler.cr
  src/placeos-driver/proxy/system.cr
  src/placeos-driver/settings/introspect.cr
Labels: focus: backend, type: documentation, type: enhancement
